# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'WeatherApp_Obj-C' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for WeatherApp_Obj-C
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'AFNetworking', '~> 2.5'
  pod 'OneSignal', '>= 2.11.2', '< 3.0'
  pod 'MaterialTextField', '~> 1.0'
#  pod 'OpenWeatherMapAPI', '>= 0.0.4'
  target 'WeatherApp_Obj-CTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'WeatherApp_Obj-CUITests' do
    # Pods for testing
  end
  
end
